// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8gnpj5mQFYwoUyjgG8FrrJK8Sxk8yR7k',
    appId: '1:663627456598:web:e642de1f7e708660ea9bf7',
    messagingSenderId: '663627456598',
    projectId: 'cui-timetable',
    authDomain: 'cui-timetable.firebaseapp.com',
    storageBucket: 'cui-timetable.appspot.com',
    measurementId: 'G-G10MXVH7XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMQKX7E4tmETXoKH72urG3tW8bYuDB1U',
    appId: '1:663627456598:android:e6a0f2b3f7763ba6ea9bf7',
    messagingSenderId: '663627456598',
    projectId: 'cui-timetable',
    storageBucket: 'cui-timetable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHwBUbYTga1qC5MbeT9W5GDuHRF5jpbA',
    appId: '1:663627456598:ios:2e2143798ca46773ea9bf7',
    messagingSenderId: '663627456598',
    projectId: 'cui-timetable',
    storageBucket: 'cui-timetable.appspot.com',
    iosClientId: '663627456598-kj8s8pl589023ssaf2d61h4hka7k611a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
